### ISSUE TITLE
OpenAPI spec not valid?

### ISSUE THREAD

**Issue by jvolkening** [ncbi/datasets#289]
Hello,

In my hands the published OpenAPI spec for Datasets (and also the latest version in git) fails validation. This appears to be caused by empty values for `example` `summary` keys, e.g.

```yaml
        examples:
          example-0:
            value: accession
            summary: 
```
I initially ran into this problem trying to use the YAML spec in an API generator, and then tried to load it in the [Swagger Editor](https://editor.swagger.io/) to check the validation and saw similar errors, e.g.

```
Structural error at paths./genome/accession/{accessions}/dataset_report.get.parameters.17.examples.example-0.summary:
should be string
```

When I used a quick script to replace all 260 or so of these empty values with 'none', the resulting file passed validation. Unfortunately the script did not preserve other formatting of the YAML so I can't easily upload these changes as a PR.
